--- 
services: 
  node: 
    build: 
      context: ./app
      dockerfile: Dockerfile-Node
    environment:
      env_file: .env
      NODE_ENV: development
    ports: 
      - "3000:3000"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-Api
    environment:
      env_file: .env
      NODE_ENV: development
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "3001:3001"
  server: 
    build: 
      context: ./server
      dockerfile: Dockerfile-Nginx
    links: 
      - node
      - api
    ports: 
      - "80:80"
  mongo:
    image: "mongo:3.6.10-stretch"
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

version: "3"
